# Generated by Django 2.0.6 on 2018-07-20 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 10, 1, 29, 322379)),
        ),
    ]
