# Generated by Django 2.0.7 on 2018-07-20 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180720_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 12, 7, 15, 726041)),
        ),
    ]
