# Generated by Django 2.0.7 on 2018-07-20 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180720_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 14, 16, 33, 756385)),
        ),
    ]
