# Generated by Django 2.0.7 on 2018-08-15 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thisid', models.PositiveIntegerField(default=1, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='设备名称')),
                ('brand', models.CharField(blank=True, choices=[('Epson', '爱普生'), ('Lenovo', '联想')], max_length=20, null=True, verbose_name='品牌')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号')),
                ('specification', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, choices=[('个', '个'), ('只', '只')], max_length=4, null=True, verbose_name='单位')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='单价')),
                ('insurance', models.CharField(blank=True, default='无', max_length=10, null=True, verbose_name='保修')),
                ('Inquiry_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='询价单价')),
                ('insurance_g', models.CharField(blank=True, default='无', max_length=10, null=True, verbose_name='保修承诺')),
                ('buy_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='采购单价')),
                ('insurance_to', models.DateField(blank=True, null=True, verbose_name='保修期至')),
                ('time_deliver', models.DateField(blank=True, null=True, verbose_name='到货期')),
                ('workflow_node', models.IntegerField(choices=[(0, '合同签约人'), (1, '商务经理'), (2, '财务经理'), (3, '营销经理'), (4, '总经理'), (5, '工程经理'), (6, '项目经理'), (7, '工程经理'), (8, '技术经理'), (9, '总经理')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '设备清单',
                'verbose_name_plural': '设备清单',
            },
        ),
        migrations.CreateModel(
            name='Device_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='设备名称')),
                ('brand', models.CharField(blank=True, choices=[('Epson', '爱普生'), ('Lenovo', '联想')], max_length=20, null=True, verbose_name='品牌')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号')),
                ('specification', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, choices=[('个', '个'), ('只', '只')], max_length=4, null=True, verbose_name='单位')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='单价')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='进货单价')),
                ('note', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='备注')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '技术经理'), (2, '商务经理'), (3, '营销经理'), (4, '总经理'), (5, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '设备更改',
                'verbose_name_plural': '设备更改',
            },
        ),
        migrations.CreateModel(
            name='Device_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='设备名字')),
                ('brand', models.CharField(blank=True, choices=[('Epson', '爱普生'), ('Lenovo', '联想')], max_length=20, null=True, verbose_name='品牌')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号')),
                ('specification', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格')),
                ('producer', models.CharField(blank=True, max_length=20, null=True, verbose_name='生产厂家')),
                ('produce_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='出产编号')),
                ('place_keep', models.CharField(blank=True, max_length=20, null=True, verbose_name='存放地点')),
                ('bill_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='单据号')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='单价')),
                ('time_install', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('record', models.CharField(blank=True, max_length=120, null=True, verbose_name='维修记录')),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='feedback_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.PositiveIntegerField(blank=True, null=True, verbose_name='序号')),
                ('item', models.CharField(blank=True, max_length=40, null=True, verbose_name='考核项目')),
                ('standard', models.CharField(blank=True, max_length=120, null=True, verbose_name='考核标准')),
                ('points', models.PositiveIntegerField(verbose_name='分值')),
                ('self_eva', models.PositiveIntegerField(default=0, verbose_name='自评分')),
                ('eva', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('note', models.CharField(blank=True, max_length=60, null=True, verbose_name='考核标准')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='项目经理奖励金额')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '技术经理'), (3, '总经理'), (4, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '项目经理考核',
                'verbose_name_plural': '项目经理考核',
            },
        ),
        migrations.CreateModel(
            name='Finish_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True, null=True, verbose_name='日期')),
                ('details', models.TextField(blank=True, null=True, verbose_name='报告')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '竣工报告',
                'verbose_name_plural': '竣工报告',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('pro_type', models.IntegerField(choices=[(0, '提交'), (1, '同意'), (2, '反对'), (3, '终止'), (4, '修改'), (5, '分流程')], default=0, verbose_name='操作类别')),
                ('memo', models.CharField(blank=True, max_length=40, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '历史事务',
                'verbose_name_plural': '历史事务',
                'ordering': ['project', 'pro_time'],
            },
        ),
        migrations.CreateModel(
            name='Material_use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='名称')),
                ('brand', models.CharField(blank=True, choices=[('Epson', '爱普生'), ('Lenovo', '联想')], max_length=20, null=True, verbose_name='品牌')),
                ('guige', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='规格')),
                ('xinhao', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='型号')),
                ('num', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit', models.CharField(blank=True, choices=[('个', '个'), ('只', '只')], max_length=4, null=True, verbose_name='单位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, max_length=8, null=True, verbose_name='单价')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '库管'), (2, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '材料领用',
                'verbose_name_plural': '材料领用',
            },
        ),
        migrations.CreateModel(
            name='Outsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='营销员')),
                ('begin_time', models.DateField(blank=True, null=True, verbose_name='计划开工时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='计划竣工时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='工作内容')),
                ('fuzeren', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='项目负责人')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='总价')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '项目经理'), (2, '工程经理'), (3, '技术经理'), (4, '总经理'), (5, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '其他费用',
                'verbose_name_plural': '其他费用',
            },
        ),
        migrations.CreateModel(
            name='Outsource_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='外包施工单位名称')),
                ('provider', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='外包施工负责人')),
                ('num', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='外包数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='单价')),
                ('note', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='备注')),
                ('outsource_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Outsource', verbose_name='所属外包项目')),
            ],
            options={
                'verbose_name': '外包项目明细',
                'verbose_name_plural': '外包项目明细',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('name', models.CharField(max_length=20, verbose_name='执行编号')),
                ('cusname', models.CharField(default='无', max_length=20, verbose_name='客户单位')),
                ('cusaddr', models.CharField(default='无', max_length=40, verbose_name='客户地址')),
                ('recname', models.CharField(default='无', max_length=20, verbose_name='收货单位')),
                ('recaddr', models.CharField(default='无', max_length=40, verbose_name='收货地址')),
                ('receiver', models.CharField(default='无', max_length=10, verbose_name='收货人')),
                ('receiverdep', models.CharField(default='无', max_length=20, verbose_name='收货部门')),
                ('receiverphone', models.CharField(default='无', max_length=20, verbose_name='收货手机')),
                ('receivertele', models.CharField(default='无', max_length=20, verbose_name='收货电话')),
                ('payer', models.CharField(default='无', max_length=10, verbose_name='付款人')),
                ('payerdep', models.CharField(default='无', max_length=20, verbose_name='付款部门')),
                ('payerphone', models.CharField(default='无', max_length=20, verbose_name='付款手机')),
                ('payertele', models.CharField(default='无', max_length=20, verbose_name='付款手机')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, max_length=10, null=True, verbose_name='合同金额')),
                ('end', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('kaipiao', models.BooleanField(default=False, verbose_name='开票')),
                ('description', models.TextField(blank=True, null=True, verbose_name='其他')),
                ('comment', models.CharField(blank=True, default='无', max_length=120, null=True, verbose_name='批示')),
                ('associated_file', models.FileField(blank=True, null=True, upload_to='project', verbose_name='文件')),
                ('workflow_node', models.IntegerField(choices=[(0, '合同签约人填写'), (1, '商务部审批并填写设备信息'), (2, '财务审批'), (3, '营销经理审批'), (4, '总经理审批'), (5, '工程经理经理指派项目经理'), (6, '项目经理施工'), (7, '工程经理审批'), (8, '技术经理审批'), (9, '总经理审批'), (10, '完成'), (11, '商务部反对，暂挂'), (12, '财务反对，暂挂'), (13, '营销经理反对，暂挂'), (14, '总经理，暂挂'), (15, '暂挂'), (16, '暂挂'), (17, '工程经理反对，暂挂'), (18, '技术经理反对，暂挂'), (19, '总经理反对，暂挂'), (20, '终止')], default=0, verbose_name='工作流节点')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='被指派项目经理', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='合同签约人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='编码')),
                ('arrived_time', models.DateTimeField(auto_now=True, verbose_name='消息时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读?')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('status', models.BooleanField(default=False, verbose_name='已完结')),
                ('memo', models.CharField(blank=True, max_length=40, null=True, verbose_name='备注')),
                ('content_type', models.IntegerField(choices=[(0, '项目'), (1, '设备更改'), (2, '材料领用'), (3, '设备最终'), (4, '竣工报告'), (5, '工时记录'), (6, '项目经理自评')], default=0, verbose_name='任务类别')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '待办事务',
                'verbose_name_plural': '待办事务',
                'ordering': ['user', '-arrived_time'],
            },
        ),
        migrations.CreateModel(
            name='work_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now_add=True, null=True, verbose_name='填写日期')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('work_content', models.CharField(blank=True, max_length=120, null=True, verbose_name='工作内容')),
                ('inside_work_hour', models.IntegerField(default=0, verbose_name='上班工时')),
                ('extra_work_hour', models.IntegerField(default=0, verbose_name='加班工时')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '技术经理'), (3, '行政经理'), (4, '完成')], default=0, verbose_name='工作流节点')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('project_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工时记录',
                'verbose_name_plural': '工时记录',
            },
        ),
        migrations.AddField(
            model_name='outsource',
            name='project_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='项目信息'),
        ),
        migrations.AddField(
            model_name='material_use',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='history',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='finish_report',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='feedback_report',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device_final',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device_change',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
    ]
