# Generated by Django 2.0.7 on 2018-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_final',
            name='product_time',
            field=models.DateField(blank=True, null=True, verbose_name='出厂日期'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='成本单价'),
        ),
        migrations.AlterField(
            model_name='feedback_report',
            name='standard',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='考核标准'),
        ),
    ]
