# Generated by Django 2.0.7 on 2018-08-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0004_auto_20180817_1019'),
    ]

