# Generated by Django 2.0.7 on 2018-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_auto_20180817_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_final',
            old_name='product_time',
            new_name='produce_time',
        ),
        migrations.AddField(
            model_name='project',
            name='niehe_hour',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='内核工时数'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_hour',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='总工时'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_mat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='材料金额'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_money',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='feedback_report',
            name='note',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='extra_work_hour',
            field=models.IntegerField(default=0, verbose_name='加班工时/单价200'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='inside_work_hour',
            field=models.IntegerField(default=0, verbose_name='上班工时/单价100'),
        ),
    ]
