# Generated by Django 2.0.7 on 2018-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0006_auto_20180820_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_change',
            name='thisid',
            field=models.PositiveIntegerField(default=1, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='device_final',
            name='thisid',
            field=models.PositiveIntegerField(default=1, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='outsource_items',
            name='thisid',
            field=models.PositiveIntegerField(default=1, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='work_hour',
            name='thisid',
            field=models.PositiveIntegerField(default=1, verbose_name='ID'),
        ),
    ]
