# Generated by Django 2.0.7 on 2018-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0007_auto_20180827_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='thisid',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='thisid',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='thisid',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outsource_items',
            name='thisid',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ID'),
        ),
    ]
