# Generated by Django 2.0.7 on 2018-08-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0009_auto_20180827_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='thisid',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='thisid',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='thisid',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outsource_items',
            name='thisid',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='ID'),
        ),
    ]
