# Generated by Django 2.0.7 on 2018-08-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0011_auto_20180827_2101'),
    ]

    operations = [

        migrations.AddField(
            model_name='material_use',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
