# Generated by Django 2.0.7 on 2019-01-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0013_device_change_change_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(blank=True, null=True, verbose_name='添加时间')),
                ('thisid', models.IntegerField(default=1, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('note', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='备注')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='修改记录')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '技术经理'), (2, '商务经理'), (3, '营销经理'), (4, '总经理'), (5, '完成')], default=0, verbose_name='工作流节点')),
                ('project_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '修改记录',
                'verbose_name_plural': '修改记录',
            },
        ),
        migrations.RemoveField(
            model_name='device_change',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='device_change',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='device_change',
            name='note',
        ),
        migrations.RemoveField(
            model_name='device_change',
            name='project_info',
        ),
        migrations.RemoveField(
            model_name='device_change',
            name='workflow_node',
        ),
    ]
