# Generated by Django 2.0.7 on 2019-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0015_device_change_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_changelog',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='总变动金额'),
        ),
    ]
