# Generated by Django 2.0.7 on 2019-01-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0017_auto_20190103_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_use',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='material_use',
            name='workflow_node',
        ),
    ]
