# Generated by Django 2.0.7 on 2019-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0018_auto_20190103_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_log',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
