# Generated by Django 2.0.7 on 2019-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0020_auto_20190103_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Inquiry_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='询价单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='采购单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='单价'),
        ),
    ]
