# Generated by Django 2.0.7 on 2019-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0021_auto_20190103_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_change',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='成本单价'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='material_use',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='outsource_items',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='单价'),
        ),
    ]
