# Generated by Django 2.0.7 on 2019-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0022_auto_20190103_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='合计单价')),
                ('total_buyprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='合计采购单价')),
            ],
        ),
        migrations.CreateModel(
            name='Worknode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(blank=True, max_length=10, null=True, verbose_name='审批文件')),
                ('flow', models.PositiveIntegerField(default=0, verbose_name='流程')),
            ],
        ),
        migrations.AddField(
            model_name='device_change',
            name='reason',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='变更原因'),
        ),
        migrations.AddField(
            model_name='outsource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='外包施工单位报价'),
        ),
        migrations.AddField(
            model_name='outsource',
            name='recom',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='推荐施工单位'),
        ),
        migrations.AddField(
            model_name='project',
            name='hour_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='工时用'),
        ),
        migrations.AlterField(
            model_name='device',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='工程内容'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='project_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='outsource_items',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=40, verbose_name='执行编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_money',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='合计费用'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='device_form',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Device_form', verbose_name='表单'),
        ),
    ]
