# Generated by Django 2.0.7 on 2019-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0023_auto_20190104_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deliver_time',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
    ]
