# Generated by Django 2.0.7 on 2019-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0024_project_deliver_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_form',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='导入EXCEL文件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hour_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='工时费'),
        ),
    ]
