# Generated by Django 2.0.7 on 2019-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0025_auto_20190104_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_form',
            options={'verbose_name': '设备表', 'verbose_name_plural': '设备表'},
        ),
        migrations.AddField(
            model_name='device',
            name='total_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='采购金额'),
        ),
        migrations.AddField(
            model_name='device',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='device_change',
            name='total_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='成本金额'),
        ),
        migrations.AddField(
            model_name='device_change',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='单位'),
        ),
    ]
