# Generated by Django 2.0.7 on 2019-01-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0027_auto_20190104_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_form',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Device_form', verbose_name='表单'),
        ),
        migrations.AlterField(
            model_name='device',
            name='project_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='device',
            name='thisid',
            field=models.IntegerField(blank=True, default=0, verbose_name='序号'),
        ),
    ]
