# Generated by Django 2.0.7 on 2019-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0028_auto_20190104_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='thisid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='序号'),
        ),
    ]
