# Generated by Django 2.0.7 on 2019-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0029_auto_20190104_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='workflow_node',
            field=models.IntegerField(blank=True, choices=[(0, '合同签约人'), (1, '商务经理'), (2, '财务经理'), (3, '营销经理'), (4, '总经理'), (5, '工程经理'), (6, '项目经理'), (7, '工程经理'), (8, '技术经理'), (9, '总经理')], default=0, null=True, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='device_form',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='导入EXCEL文件'),
        ),
    ]
