# Generated by Django 2.0.7 on 2019-01-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0030_auto_20190105_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devive_finalform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='导入EXCEL文件')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '库管'), (3, '完成')], default=0, verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.AlterModelOptions(
            name='device_final',
            options={'verbose_name': '设备信息单项', 'verbose_name_plural': '设备信息单项'},
        ),
        migrations.RemoveField(
            model_name='device_final',
            name='agreed',
        ),
        migrations.AlterField(
            model_name='device_form',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='导入EXCEL文件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='associated_file',
            field=models.FileField(blank=True, null=True, upload_to='excel', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='devive_finalform',
            name='project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device_final',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Devive_finalform', verbose_name='表单'),
        ),
    ]
