# Generated by Django 2.0.7 on 2019-01-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0031_auto_20190106_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devive_finalform',
            new_name='Device_finalform',
        ),
    ]
