# Generated by Django 2.0.7 on 2019-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0033_auto_20190106_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_final',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌'),
        ),
    ]
