# Generated by Django 2.0.7 on 2019-01-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0035_auto_20190106_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_report',
            name='idnum',
            field=models.PositiveIntegerField(blank=True, max_length=8, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.IntegerField(default=0, max_length=8, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='worknode',
            name='doc',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='审批文件'),
        ),
    ]
