# Generated by Django 2.0.7 on 2019-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0036_auto_20190106_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_report',
            name='idnum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='worknode',
            name='doc',
            field=models.IntegerField(blank=True, null=True, verbose_name='审批文件'),
        ),
    ]
