# Generated by Django 2.0.7 on 2019-01-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0037_auto_20190106_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknode',
            name='doc',
            field=models.IntegerField(blank=True, choices=[(1, '总流程'), (2, '其他费用'), (3, '设备更改'), (4, '施工材料'), (5, '工时记录'), (6, '竣工报告'), (7, '自评表')], null=True, verbose_name='审批文件'),
        ),
    ]
