# Generated by Django 2.0.7 on 2019-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0038_auto_20190106_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worknode',
            options={'verbose_name': '流程', 'verbose_name_plural': '流程'},
        ),
        migrations.AlterField(
            model_name='project',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '合同签约人填写'), (1, '营销经理审批'), (2, '商务部审批并填写设备信息'), (3, '技术经理审批'), (4, '财务审批'), (5, '总经理审批'), (6, '工程经理经理指派项目经理'), (7, '项目经理施工'), (8, '工程经理审批'), (9, '技术经理审批'), (10, '总经理审批'), (11, '完成'), (12, '终止')], default=0, verbose_name='工作流节点'),
        ),
    ]
