# Generated by Django 2.0.7 on 2019-01-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0039_auto_20190107_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknode',
            name='flow',
            field=models.CharField(default=0, max_length=12, verbose_name='流程'),
        ),
    ]
