# Generated by Django 2.0.7 on 2019-01-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0040_auto_20190107_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, max_length=8, null=True, verbose_name='项目经理奖励金额')),
                ('agreed', models.BooleanField(default=False, verbose_name='已同意')),
                ('total_self', models.PositiveIntegerField(blank=True, null=True, verbose_name='总自评')),
                ('total_point', models.PositiveIntegerField(blank=True, null=True, verbose_name='总得分')),
                ('workflow_node', models.IntegerField(choices=[(0, '等待'), (1, '工程经理'), (2, '技术经理'), (3, '总经理'), (4, '完成')], default=0, verbose_name='工作流节点')),
                ('project_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目经理考核',
                'verbose_name_plural': '项目经理考核',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback_report',
            options={'verbose_name': '项目经理考核单项', 'verbose_name_plural': '项目经理考核单项'},
        ),
        migrations.RemoveField(
            model_name='feedback_report',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='feedback_report',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='feedback_report',
            name='project_info',
        ),
        migrations.RemoveField(
            model_name='feedback_report',
            name='workflow_node',
        ),
        migrations.AddField(
            model_name='feedback_report',
            name='feedback_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='表单'),
        ),
        migrations.AlterField(
            model_name='worknode',
            name='doc',
            field=models.IntegerField(blank=True, choices=[(1, '总流程'), (2, '其他费用'), (3, '设备更改'), (4, '施工材料'), (5, '工时记录'), (6, '竣工报告'), (7, '自评表'), (8, '设备信息表')], null=True, verbose_name='审批文件'),
        ),
    ]
