# Generated by Django 2.0.7 on 2019-01-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0041_auto_20190107_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_report',
            name='feedback_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.feedback_form', verbose_name='表单'),
        ),
    ]
