# Generated by Django 2.0.7 on 2019-01-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0043_auto_20190108_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_changelog',
            name='thisid',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='device_changelog',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '营销经理'), (2, '技术经理'), (3, '商务经理'), (4, '总经理'), (6, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='device_finalform',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '工程经理'), (2, '库管'), (4, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='feedback_form',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '工程经理'), (2, '技术经理'), (3, '技术中心经理'), (4, '总经理'), (6, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='finish_report',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '工程经理'), (3, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '库管'), (3, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '技术中心经理'), (2, '总经理'), (4, '完成')], default=0, verbose_name='工作流节点'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cusaddr',
            field=models.CharField(default='', max_length=40, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cusname',
            field=models.CharField(default='', max_length=20, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliver_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='收款日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payer',
            field=models.CharField(default='', max_length=10, verbose_name='付款人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payerdep',
            field=models.CharField(default='', max_length=20, verbose_name='付款部门'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payerphone',
            field=models.CharField(default='', max_length=20, verbose_name='付款手机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payertele',
            field=models.CharField(default='', max_length=20, verbose_name='付款电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recaddr',
            field=models.CharField(default='', max_length=40, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiver',
            field=models.CharField(default='', max_length=10, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiverdep',
            field=models.CharField(default='', max_length=20, verbose_name='收货部门'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiverphone',
            field=models.CharField(default='', max_length=20, verbose_name='收货手机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receivertele',
            field=models.CharField(default='', max_length=20, verbose_name='收货电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recname',
            field=models.CharField(default='', max_length=20, verbose_name='收货单位'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content_type',
            field=models.IntegerField(choices=[(1, '总流程'), (2, '其他费用'), (3, '设备更改'), (4, '施工材料'), (5, '工时记录'), (6, '竣工报告'), (7, '自评表'), (8, '设备信息表')], default=0, verbose_name='任务类别'),
        ),
        migrations.AlterField(
            model_name='work_report',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '工程经理'), (2, '技术经理'), (3, '技术中心经理'), (4, '总经理'), (6, '完成')], default=0, verbose_name='工作流节点'),
        ),
    ]
