# Generated by Django 2.0.7 on 2019-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0044_auto_20190109_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tiaojian',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='付款条件'),
        ),
        migrations.AlterField(
            model_name='device',
            name='time_deliver',
            field=models.DateField(blank=True, null=True, verbose_name='到货时间'),
        ),
    ]
