# Generated by Django 2.0.7 on 2019-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0045_auto_20190109_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='insurance_to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='保修期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '商务助理'), (2, '商务经理'), (3, '营销经理'), (4, '技术中心经理'), (5, '财务经理'), (6, '总经理'), (7, '工程经理'), (8, '普通员工'), (9, '技术经理'), (10, '行政经理'), (11, '总经理'), (13, '完成')], default=0, verbose_name='工作流节点'),
        ),
    ]
