# Generated by Django 2.0.7 on 2019-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0046_auto_20190109_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_out',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='其他费用'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='device_form',
            name='total_buyprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='合计采购金额'),
        ),
        migrations.AlterField(
            model_name='device_form',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='合计金额'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cusaddr',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cusname',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payer',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='付款人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payerdep',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='付款部门'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payerphone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='付款手机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payertele',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='付款电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recaddr',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiverdep',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='收货部门'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiverphone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='收货手机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='receivertele',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='收货电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recname',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='收货单位'),
        ),
    ]
