# Generated by Django 2.0.7 on 2019-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0047_auto_20190110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsource',
            name='fuzeren',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='金额'),
        ),
    ]
