# Generated by Django 2.0.7 on 2019-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0048_auto_20190110_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsource_items',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='外包施工单位报价'),
        ),
    ]
