# Generated by Django 2.0.7 on 2019-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0050_auto_20190110_1539'),
    ]

    operations = [
    ]
