# Generated by Django 2.0.7 on 2019-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0052_auto_20190110_1555'),
    ]

    operations = [

    ]
