# Generated by Django 2.0.7 on 2019-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0053_work_hour_extra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_hour',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='合计绩效工资'),
        ),
    ]
