# Generated by Django 2.0.7 on 2019-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0054_work_hour_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_report',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='总计'),
        ),
    ]
