# Generated by Django 2.0.7 on 2019-01-11 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0055_auto_20190110_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_use',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='金额'),
        ),

        migrations.AlterField(
            model_name='feedback_report',
            name='note',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='material_use',
            name='num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='material_use',
            name='unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='施工人员姓名'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='extra_work_hour',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, max_length=8, null=True, verbose_name='加班工时系数/单价200'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='inside_work_hour',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, max_length=8, null=True, verbose_name='上班工时系数/单价100'),
        ),
        migrations.AlterField(
            model_name='work_report',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='合计绩效工资'),
        ),
    ]
