# Generated by Django 2.0.7 on 2019-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0056_auto_20190111_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_log',
            name='thisid',
        ),
    ]
