# Generated by Django 2.0.7 on 2019-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0057_auto_20190111_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_hour',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='加班绩效工资'),
        ),
        migrations.AddField(
            model_name='work_hour',
            name='inside_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, max_length=8, null=True, verbose_name='上班绩效工资'),
        ),
        migrations.AddField(
            model_name='work_hour',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Inquiry_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, max_length=8, null=True, verbose_name='询价单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, max_length=8, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='produce_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='出厂编号'),
        ),
        migrations.AlterField(
            model_name='material_use',
            name='thisid',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
