# Generated by Django 2.0.7 on 2019-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0058_auto_20190114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, max_length=8, null=True, verbose_name='金额'),
        ),
    ]
