# Generated by Django 2.0.7 on 2019-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0059_auto_20190114_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Inquiry_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='询价单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='采购单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='采购金额'),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='device_form',
            name='total_buyprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='合计采购金额'),
        ),
        migrations.AlterField(
            model_name='device_form',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=8, null=True, verbose_name='合计金额'),
        ),
        migrations.AlterField(
            model_name='feedback_form',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, max_length=8, null=True, verbose_name='项目经理奖励金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True, verbose_name='合同金额'),
        ),
    ]
