# Generated by Django 2.0.7 on 2019-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0060_auto_20190114_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='workflow_node',
        ),
        migrations.AddField(
            model_name='device_final',
            name='originID',
            field=models.IntegerField(blank=True, null=True, verbose_name='原项目序号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Inquiry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=8, null=True, verbose_name='询价单价'),
        ),
        migrations.AlterField(
            model_name='device',
            name='insurance',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='保修'),
        ),
        migrations.AlterField(
            model_name='device',
            name='insurance_g',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='保修承诺'),
        ),
        migrations.AlterField(
            model_name='device_change',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='device_changelog',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='material_use',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='outsource_items',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='work_hour',
            name='thisid',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='work_report',
            name='workflow_node',
            field=models.IntegerField(choices=[(0, '等待填写人发起'), (1, '工程经理'), (2, '技术中心经理'), (3, '行政经理'), (5, '完成')], default=0, verbose_name='工作流节点'),
        ),
    ]
