# Generated by Django 2.0.7 on 2019-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0061_auto_20190115_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='型号'),
        ),
    ]
