# Generated by Django 2.0.7 on 2019-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0062_auto_20190117_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='型号'),
        ),
    ]
