# Generated by Django 2.0.7 on 2019-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0063_auto_20190117_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型号'),
        ),
    ]
