# Generated by Django 2.0.7 on 2019-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0064_auto_20190117_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='设备名称'),
        ),
    ]
