# Generated by Django 2.0.7 on 2019-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0065_auto_20190117_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='设备名称'),
        ),
    ]
