# Generated by Django 2.0.7 on 2019-01-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0067_auto_20190117_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_final',
            name='name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='producer',
            field=models.TextField(blank=True, null=True, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='record',
            field=models.TextField(blank=True, null=True, verbose_name='维修记录'),
        ),
        migrations.AlterField(
            model_name='device_final',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hour_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='工时费'),
        ),
        migrations.AlterField(
            model_name='project',
            name='niehe_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='内核工时数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='总工时'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='合计费用'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_out',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='其他费用'),
        ),
    ]
