# Generated by Django 2.0.7 on 2019-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0069_auto_20190117_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-pro_time', 'project'], 'verbose_name': '历史事务', 'verbose_name_plural': '历史事务'},
        ),
        migrations.RemoveField(
            model_name='device_final',
            name='originID',
        ),
        migrations.AddField(
            model_name='device_changelog',
            name='device',
            field=models.ManyToManyField(null=True, to='basedata.Device', verbose_name='选择设备'),
        ),
        migrations.AddField(
            model_name='device_finalform',
            name='device',
            field=models.ManyToManyField(null=True, to='basedata.Device', verbose_name='选择设备'),
        ),
        migrations.AlterField(
            model_name='device_changelog',
            name='log',
            field=models.TextField(blank=True, default='', null=True, verbose_name='报告'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pro_type',
            field=models.IntegerField(choices=[(0, '提交'), (1, '同意'), (2, '反对'), (3, '终止')], default=0, verbose_name='操作类别'),
        ),
    ]
