# Generated by Django 2.0.7 on 2019-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0070_auto_20190410_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_changelog',
            name='device',
            field=models.ManyToManyField(blank=True, to='basedata.Device', verbose_name='选择设备'),
        ),
        migrations.AlterField(
            model_name='device_finalform',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='设备', to='basedata.Device', verbose_name='选择设备'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='其他'),
        ),
    ]
