# Generated by Django 2.0.7 on 2019-07-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0071_auto_20190412_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备单项', 'verbose_name_plural': '设备单项'},
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='批示'),
        ),

    ]
