# Generated by Django 2.0.7 on 2019-07-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0072_auto_20190718_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_report',
            options={'verbose_name': '', 'verbose_name_plural': '工时记录'},
        ),
        migrations.AddField(
            model_name='device_change',
            name='memo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='device_changelog',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='device_finalform',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='feedback_form',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='finish_report',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='outsource',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
        migrations.AlterField(
            model_name='work_report',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='已审批完成'),
        ),
    ]
