# Generated by Django 2.0.7 on 2019-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0073_auto_20190719_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsource',
            name='associated_file',
            field=models.FileField(blank=True, null=True, upload_to='excel', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='project',
            name='reward',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='项目经理奖励'),
        ),
    ]
